# change the followings to match your Github username and repo name
baseurl: "/" # the name of your github repo
url: "https://harrywang.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Terack"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: stone # indigo|yellow|pink|green|stone|

# homepage information
author: Terack
author-bio: Web Developer && Movie Creator  # change to false to hide
author-image: stair.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/terackr
facebook: false
instagram: false
github: https://github.com/terackr
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-postcss-v2
